### ISSUE TITLE
About the result of seq008 in Deep Deform test set!

### ISSUE THREAD

**Issue by phamtrongthang123** [USTC3DV/NDR-code#4]
Thank you for sharing this wonderful works. I am trying to reproduce the results in Figure 1. However, I failed and stuck on what to do next. I want to ask about the config of this sample in Figure 1 in your paper. 
![image](https://user-images.githubusercontent.com/17172232/203296281-cb919960-4759-4456-a79a-c79c099cad4a.png)

I think the sample is from seq008. However, using the provided config of this repo (120,000 iterations with 5e-4 lr) produced an underwhelming results (not as good as in Figure 1). Note that I followed strictly with the described preprocessing steps (delete invalid points and save as xyz and scale step3.py to ensure valid points inside unit ball), but I don't know if this is a problem on preprocessing, and I think maybe we can tweak the config, but I have no idea how to.

Below I show the meshes at (0,200,400,600,800)-th frames and validation in rgb and normal.
![image](https://user-images.githubusercontent.com/17172232/203297046-f92b8ed6-ffd1-4d18-a9b0-089b5a65562c.png)
https://user-images.githubusercontent.com/17172232/203296534-238b4cc6-fac8-4763-abbf-2c9366953b7e.mp4
https://user-images.githubusercontent.com/17172232/203297124-489f5358-2b4c-451e-befa-ba97ccea1e09.mp4

The link to tensorboard log: https://drive.google.com/drive/folders/1yQ7WlEi8q0ULSRnFyP58dPBgf_3g-gpE?usp=sharing
Please help me. Thank you very much.

**Comment by RainbowRui** [comment]
After viewing the video you provided, I noticed that the results do not seem to converge to a stable solution. Have you attempted to increase the number of iterations or adjust the weight of the color loss to help improve the convergence?

**Comment by phamtrongthang123** [comment]
Hi @RainbowRui, thank you for your reply! I haven't increased the number of iterations as it took me 5-7 days on my machine to produce the results. About the color loss, I am not sure what direction should I tweak, is it increasing the weight? 

And I just want to confirm, are the images from your paper, mentioned above, from seq008 video of Deep Deform?

**Comment by RainbowRui** [comment]
Hi @phamtrongthang123, the images in my paper correspond to the "seq011" video of the Deep Deform test dataset. However, I don't think it matters much. As our NDR optimizes slowly, I recommend validating the model using 200-300 frames of a video. If your GPU memory is sufficient, you can increase the number of `train.batch_size` in the configuration file. If the optimized result lacks detail, you could decrease `train.geo_weight` in the configuration file, since this will add more details through the color loss term. Please feel free to give this a try! If you have any questions, please let me know.

**Comment by phamtrongthang123** [comment]
Thank you so much! That makes sense. I will try it later.
